"""
Rebuild the book's markdown from state.json sections.

This regenerates book.clean.md from scratch, taking section content directly
from state.json (which has retried sections like 1.2 and 1.5 with new content).
Then re-renders to PDF.
"""
import json
import re
from pathlib import Path

OUT_DIR = Path("/Users/vudang/PythonLab/AgentDeepLearning/files/output/runs/llm_book_v36")
STATE_PATH = OUT_DIR / "state.json"
OUTLINE_PATH = OUT_DIR / "outline_profile.json"
TOPIC_PATH = OUT_DIR / "topic_profile.json"
BOOK_OUT = OUT_DIR / "book.clean.md"


def polish_title(title: str) -> str:
    if not title:
        return title
    parts = title.rsplit(", and ", 1)
    if len(parts) == 2:
        left, tail = parts
        if ":" in left:
            topic, subtitle = left.split(":", 1)
            topic_norm = re.sub(r"[^a-z0-9]", "", topic.lower())
            tail_norm = re.sub(r"[^a-z0-9]", "", tail.lower())
            if topic_norm == tail_norm:
                return f"{topic.strip()}: {subtitle.strip()}"
    return title


def main():
    state = json.load(open(STATE_PATH))
    outline = json.load(open(OUTLINE_PATH))
    topic = json.load(open(TOPIC_PATH))
    sections = state.get("sections", {})

    # Title + subtitle
    title = outline.get("title", topic.get("title", "LLM Book"))
    subtitle = outline.get("subtitle", "")

    lines = [f"# {title}", ""]
    if subtitle:
        lines += [f"_{subtitle}_", ""]
    lines += ["Generated by Agentic Deep Research v3 (post-retry edition)", ""]

    # Chapters
    chapter_idx = {}
    for ch in outline.get("chapters", []):
        n = ch.get("n")
        chapter_idx[n] = ch

    # We need to know which section belongs to which chapter.
    # Outline sections are 1..7 per chapter. State key is "1.1".."40.7".
    # We map chapter n -> list of section records from state.
    for n_str in sorted(chapter_idx.keys(), key=int):
        ch = chapter_idx[n_str]
        ch_title = polish_title(ch.get("t", f"Chapter {n_str}"))
        lines.append(f"# {ch_title}")
        lines.append("")

        out_secs = ch.get("sections", [])
        for sec in out_secs:
            sec_n = sec.get("n")
            sec_title = polish_title(sec.get("t", f"Section {n_str}.{sec_n}"))
            # Find state key
            skey = f"{n_str}.{sec_n}"
            sec_data = sections.get(skey, {})
            if sec_data.get("quality") == "BLOCKED":
                # Skip blocked sections
                lines.append(f"## {skey} {sec_title}")
                lines.append("")
                reason = sec_data.get("block_reason", "unknown")
                lines.append(f"> **[Section {skey} BLOCKED during pipeline]** Reason: {reason[:200]}")
                lines.append("")
                continue
            content = sec_data.get("content", "").strip()
            if not content:
                lines.append(f"## {skey} {sec_title}")
                lines.append("")
                lines.append("> **[Section has no content]**")
                lines.append("")
                continue
            lines.append(f"## {skey} {sec_title}")
            lines.append("")
            lines.append(content)
            lines.append("")

    # References (re-append)
    refs_path = OUT_DIR / "book.references.md"
    if refs_path.exists():
        refs_content = refs_path.read_text()
        # Strip the standalone header (we'll keep just the body)
        body = re.sub(r"^# LLM Agents.*?---\n", "", refs_content, count=1, flags=re.DOTALL)
        lines.append("---")
        lines.append("")
        lines.append(body)

    BOOK_OUT.write_text("\n".join(lines))
    print(f"Rebuilt {BOOK_OUT}")
    wc = sum(len(l.split()) for l in lines)
    print(f"  ~{wc} words")


if __name__ == "__main__":
    main()
